### ISSUE TITLE
Unknown format template 'keyvalue'

### ISSUE THREAD

**Issue by jurgenhaas** [ArunMj/fluent-plugin-keyvalue-parser#1]
I have installed your gem and put the following in my config:

```
<filter app.matterbridge>
  type parser
  format keyvalue
  key_name log
  pair_delimiter " "
  key_value_separator "="
</filter>
```

Then I'm getting the above error when trying to start td-agent. I'm using td-agent 0.12.31

Any idea what I'm doing wrong?

**Comment by nom3ad** [comment]
Thanks to @jurgenhaas  for pointing out the bug. it has been fixed.
